// src/mockData.ts
import { User, Trip, Booking, Car, Chat, ChatMessage, Review } from "./types";

export const USERS_STORAGE_KEY = "rideshare-users";

export const mockUsers: User[] = [
  {
    id: "u1",
    fullName: "Иван Петров",
    email: "ivan.petrov@example.com",
    rating: 4.9,
    carName: "Toyota Camry, черный",
    about:
      "Езжу аккуратно, заранее подтверждаю детали маршрута и люблю, когда поездка проходит спокойно.",
    location: "Барнаул",
  },
  {
    id: "u2",
    fullName: "Анна Смирнова",
    email: "anna.smirnova@example.com",
    rating: 4.8,
    carName: "Kia Rio, белый",
    about:
      "Часто езжу между Барнаулом и Горным Алтаем. Беру небольшие посылки и пассажиров с багажом.",
    location: "Барнаул",
  },
  {
    id: "u3",
    fullName: "Алексей Морозов",
    email: "alexey.morozov@example.com",
    rating: 4.7,
    carName: "Volkswagen Transporter, серый",
    about:
      "Помогаю с междугородними перевозками и переездами. Бережно отношусь к грузу.",
    location: "Новосибирск",
  },
  {
    id: "u4",
    fullName: "Мария Волкова",
    email: "maria.volkova@example.com",
    rating: 5,
    carName: "Hyundai Solaris, синий",
    about:
      "Пунктуальный водитель, заранее предупреждаю об остановках и изменениях по времени.",
    location: "Барнаул",
  },
  {
    id: "u5",
    fullName: "Дмитрий Соколов",
    email: "dmitry.sokolov@example.com",
    rating: 4.6,
    carName: "ГАЗель Next, белый",
    about:
      "Работаю с грузовыми поездками по Алтайскому краю, могу помочь с погрузкой по договоренности.",
    location: "Бийск",
  },
];

export const mockCars: Car[] = [
  {
    id: "car-u1",
    ownerId: "u1",
    brand: "Toyota",
    model: "Camry",
    color: "черный",
    plate: "А123ВС22",
  },
  {
    id: "car-u2",
    ownerId: "u2",
    brand: "Kia",
    model: "Rio",
    color: "белый",
    plate: "В456ОР22",
  },
  {
    id: "car-u3",
    ownerId: "u3",
    brand: "Volkswagen",
    model: "Transporter",
    color: "серый",
    plate: "Е789КХ22",
  },
  {
    id: "car-u4",
    ownerId: "u4",
    brand: "Hyundai",
    model: "Solaris",
    color: "синий",
    plate: "М234ТТ22",
  },
  {
    id: "car-u5",
    ownerId: "u5",
    brand: "ГАЗель",
    model: "Next",
    color: "белый",
    plate: "Н567РУ22",
  },
];

export const mockTrips: Trip[] = [
  {
    id: "passenger-1",
    fromCity: "Барнаул",
    toCity: "Новосибирск",
    date: "2026-07-05",
    departureTime: "08:00",
    arrivalTime: "12:10",
    driver: mockUsers[0],
    pricePerSeat: 900,
    freeSeats: 3,
    type: "passenger",
    stops: ["Тальменка", "Черепаново"],
    carId: "car-u1",
    amenities: {
      childSeat: true,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
  },
  {
    id: "passenger-2",
    fromCity: "Барнаул",
    toCity: "Горно-Алтайск",
    date: "2026-07-07",
    departureTime: "07:30",
    arrivalTime: "12:20",
    driver: mockUsers[1],
    pricePerSeat: 1600,
    freeSeats: 2,
    type: "passenger",
    stops: ["Бийск", "Сростки"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
  },
  {
    id: "passenger-3",
    fromCity: "Новосибирск",
    toCity: "Барнаул",
    date: "2026-07-08",
    departureTime: "18:20",
    arrivalTime: "22:30",
    driver: mockUsers[3],
    pricePerSeat: 950,
    freeSeats: 4,
    type: "passenger",
    stops: ["Искитим"],
    carId: "car-u4",
    amenities: {
      childSeat: true,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
  },
  {
    id: "passenger-4",
    fromCity: "Барнаул",
    toCity: "Кемерово",
    date: "2026-07-10",
    departureTime: "09:15",
    arrivalTime: "16:05",
    driver: mockUsers[2],
    pricePerSeat: 1800,
    freeSeats: 2,
    type: "passenger",
    stops: ["Новосибирск", "Ленинск-Кузнецкий"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-5",
    fromCity: "Бийск",
    toCity: "Барнаул",
    date: "2026-07-12",
    departureTime: "14:00",
    arrivalTime: "17:10",
    driver: mockUsers[4],
    pricePerSeat: 700,
    freeSeats: 3,
    type: "passenger",
    stops: ["Зональное"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "cargo-1",
    fromCity: "Барнаул",
    toCity: "Новосибирск",
    date: "2026-07-05",
    departureTime: "10:00",
    arrivalTime: "14:30",
    driver: mockUsers[2],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Тальменка"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["мебель", "личные вещи"],
    cargoLength: 2.1,
    cargoHeight: 1.8,
    cargoWidth: 1.1,
    cargoWeight: 100,
    cargoVehicleType: "фургон",
    cargoServices: ["помощь с погрузкой", "крепление груза"],
    pricePerCar: 8500,
  },
  {
    id: "cargo-2",
    fromCity: "Барнаул",
    toCity: "Бийск",
    date: "2026-07-06",
    departureTime: "11:20",
    arrivalTime: "14:40",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Зональное"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["техника"],
    cargoLength: 1.7,
    cargoHeight: 1.9,
    cargoWidth: 0.8,
    cargoWeight: 100,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["помощь с разгрузкой", "доставка до двери"],
    pricePerCar: 6000,
  },
  {
    id: "cargo-3",
    fromCity: "Новосибирск",
    toCity: "Барнаул",
    date: "2026-07-09",
    departureTime: "09:00",
    arrivalTime: "13:20",
    driver: mockUsers[0],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    carId: "car-u1",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
    cargoTypes: ["документы", "посылка"],
    cargoLength: 0.4,
    cargoHeight: 0.2,
    cargoWidth: 0.3,
    cargoWeight: 10,
    cargoVehicleType: "легковой автомобиль",
    cargoServices: ["доставка до двери", "фотоотчёт"],
    pricePerCar: 4500,
  },
  {
    id: "cargo-4",
    fromCity: "Барнаул",
    toCity: "Кемерово",
    date: "2026-07-11",
    departureTime: "06:45",
    arrivalTime: "13:50",
    driver: mockUsers[3],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Новосибирск"],
    carId: "car-u4",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
    cargoTypes: ["личные вещи"],
    cargoLength: 1.2,
    cargoHeight: 0.8,
    cargoWidth: 0.7,
    cargoWeight: 50,
    cargoVehicleType: "универсал",
    cargoServices: ["помощь с погрузкой"],
    pricePerCar: 7200,
  },
  {
    id: "cargo-5",
    fromCity: "Горно-Алтайск",
    toCity: "Барнаул",
    date: "2026-07-13",
    departureTime: "15:30",
    arrivalTime: "20:00",
    driver: mockUsers[1],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Бийск"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
    cargoTypes: ["посылка", "хрупкий груз"],
    cargoLength: 0.9,
    cargoHeight: 0.6,
    cargoWidth: 0.5,
    cargoWeight: 80,
    cargoVehicleType: "минивэн",
    cargoServices: ["фотоотчёт"],
    pricePerCar: 3500,
  },
];

export const mockBookings: Booking[] = [];

export const mockReviews: Review[] = [
  {
    id: "review-1",
    targetUserId: "u1",
    authorId: "u2",
    rating: 5,
    text: "Иван приехал заранее, помог с багажом и спокойно довез до места.",
    createdAt: "2026-04-20T10:00:00.000Z",
    tripId: "passenger-1",
  },
  {
    id: "review-2",
    targetUserId: "u1",
    authorId: "u4",
    rating: 5,
    text: "Комфортная поездка, чистая машина и понятная коммуникация по маршруту.",
    createdAt: "2026-05-02T15:30:00.000Z",
    tripId: "cargo-3",
  },
  {
    id: "review-3",
    targetUserId: "u2",
    authorId: "u1",
    rating: 5,
    text: "Анна быстро отвечает и аккуратно планирует остановки. Все прошло по договоренности.",
    createdAt: "2026-05-05T09:15:00.000Z",
    tripId: "passenger-2",
  },
  {
    id: "review-4",
    targetUserId: "u3",
    authorId: "u5",
    rating: 4,
    text: "Груз доставлен без повреждений, водитель был на связи на всем маршруте.",
    createdAt: "2026-05-10T12:45:00.000Z",
    tripId: "cargo-1",
  },
  {
    id: "review-5",
    targetUserId: "u4",
    authorId: "u2",
    rating: 5,
    text: "Мария очень пунктуальна, в машине чисто и спокойно.",
    createdAt: "2026-05-12T17:20:00.000Z",
    tripId: "passenger-3",
  },
  {
    id: "review-6",
    targetUserId: "u5",
    authorId: "u3",
    rating: 4,
    text: "Дмитрий помог с крупной техникой и заранее уточнил все детали перевозки.",
    createdAt: "2026-05-18T08:10:00.000Z",
    tripId: "cargo-2",
  },
];

export const mockChats: Chat[] = [];

export const mockChatMessages: ChatMessage[] = [];
