// src/mockData.ts
import { User, Trip, Booking, Car, Chat, ChatMessage, Review } from "./types";

export const USERS_STORAGE_KEY = "rideshare-users";

export const mockUsers: User[] = [
  {
    id: "u1",
    fullName: "Иван Петров",
    email: "ivan.petrov@example.com",
    rating: 4.9,
    carName: "Toyota Camry, черный",
    about:
      "Езжу аккуратно, заранее подтверждаю детали маршрута и люблю, когда поездка проходит спокойно.",
    location: "Барнаул",
  },
  {
    id: "u2",
    fullName: "Анна Смирнова",
    email: "anna.smirnova@example.com",
    rating: 4.8,
    carName: "Kia Rio, белый",
    about:
      "Часто езжу между Барнаулом и Горным Алтаем. Беру небольшие посылки и пассажиров с багажом.",
    location: "Барнаул",
  },
  {
    id: "u3",
    fullName: "Алексей Морозов",
    email: "alexey.morozov@example.com",
    rating: 4.7,
    carName: "Volkswagen Transporter, серый",
    about:
      "Помогаю с междугородними перевозками и переездами. Бережно отношусь к грузу.",
    location: "Новосибирск",
  },
  {
    id: "u4",
    fullName: "Мария Волкова",
    email: "maria.volkova@example.com",
    rating: 5,
    carName: "Hyundai Solaris, синий",
    about:
      "Пунктуальный водитель, заранее предупреждаю об остановках и изменениях по времени.",
    location: "Барнаул",
  },
  {
    id: "u5",
    fullName: "Дмитрий Соколов",
    email: "dmitry.sokolov@example.com",
    rating: 4.6,
    carName: "ГАЗель Next, белый",
    about:
      "Работаю с грузовыми поездками по Алтайскому краю, могу помочь с погрузкой по договоренности.",
    location: "Бийск",
  },
];

export const mockCars: Car[] = [
  {
    id: "car-u1",
    ownerId: "u1",
    brand: "Toyota",
    model: "Camry",
    color: "черный",
    plate: "А123ВС22",
  },
  {
    id: "car-u2",
    ownerId: "u2",
    brand: "Kia",
    model: "Rio",
    color: "белый",
    plate: "В456ОР22",
  },
  {
    id: "car-u3",
    ownerId: "u3",
    brand: "Volkswagen",
    model: "Transporter",
    color: "серый",
    plate: "Е789КХ22",
  },
  {
    id: "car-u4",
    ownerId: "u4",
    brand: "Hyundai",
    model: "Solaris",
    color: "синий",
    plate: "М234ТТ22",
  },
  {
    id: "car-u5",
    ownerId: "u5",
    brand: "ГАЗель",
    model: "Next",
    color: "белый",
    plate: "Н567РУ22",
  },
];

export const mockTrips: Trip[] = [
  {
    id: "passenger-1",
    fromCity: "Барнаул",
    toCity: "Новосибирск",
    date: "2026-07-05",
    departureTime: "08:00",
    arrivalTime: "12:10",
    driver: mockUsers[0],
    pricePerSeat: 900,
    freeSeats: 3,
    type: "passenger",
    stops: ["Тальменка", "Черепаново"],
    carId: "car-u1",
    amenities: {
      childSeat: true,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
  },
  {
    id: "passenger-2",
    fromCity: "Барнаул",
    toCity: "Горно-Алтайск",
    date: "2026-07-07",
    departureTime: "07:30",
    arrivalTime: "12:20",
    driver: mockUsers[1],
    pricePerSeat: 1600,
    freeSeats: 2,
    type: "passenger",
    stops: ["Бийск", "Сростки"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
  },
  {
    id: "passenger-3",
    fromCity: "Новосибирск",
    toCity: "Барнаул",
    date: "2026-07-08",
    departureTime: "18:20",
    arrivalTime: "22:30",
    driver: mockUsers[3],
    pricePerSeat: 950,
    freeSeats: 4,
    type: "passenger",
    stops: ["Искитим"],
    carId: "car-u4",
    amenities: {
      childSeat: true,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
  },
  {
    id: "passenger-4",
    fromCity: "Барнаул",
    toCity: "Кемерово",
    date: "2026-07-10",
    departureTime: "09:15",
    arrivalTime: "16:05",
    driver: mockUsers[2],
    pricePerSeat: 1800,
    freeSeats: 2,
    type: "passenger",
    stops: ["Новосибирск", "Ленинск-Кузнецкий"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-5",
    fromCity: "Бийск",
    toCity: "Барнаул",
    date: "2026-07-12",
    departureTime: "14:00",
    arrivalTime: "17:10",
    driver: mockUsers[4],
    pricePerSeat: 700,
    freeSeats: 3,
    type: "passenger",
    stops: ["Зональное"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "event-basta-trip-1",
    fromCity: "Барнаул",
    toCity: "Новосибирск",
    date: "2026-07-25",
    departureTime: "14:30",
    arrivalTime: "18:45",
    driver: mockUsers[0],
    pricePerSeat: 1050,
    freeSeats: 3,
    type: "passenger",
    stops: ["Новоалтайск", "Тальменка", "Черепаново"],
    carId: "car-u1",
    amenities: {
      childSeat: true,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
  },
  {
    id: "event-basta-trip-2",
    fromCity: "Барнаул",
    toCity: "Новосибирск",
    date: "2026-07-25",
    departureTime: "15:20",
    arrivalTime: "19:25",
    driver: mockUsers[3],
    pricePerSeat: 1150,
    freeSeats: 4,
    type: "passenger",
    stops: ["Тальменка", "Искитим"],
    carId: "car-u4",
    amenities: {
      childSeat: true,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
  },
  {
    id: "event-sirotkin-trip-1",
    fromCity: "Барнаул",
    toCity: "Красноярск",
    date: "2026-07-26",
    departureTime: "07:00",
    arrivalTime: "18:10",
    driver: mockUsers[1],
    pricePerSeat: 2600,
    freeSeats: 2,
    type: "passenger",
    stops: ["Новосибирск", "Кемерово", "Ачинск"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
  },
  {
    id: "event-sirotkin-trip-2",
    fromCity: "Барнаул",
    toCity: "Красноярск",
    date: "2026-07-26",
    departureTime: "08:15",
    arrivalTime: "19:30",
    driver: mockUsers[2],
    pricePerSeat: 2400,
    freeSeats: 5,
    type: "passenger",
    stops: ["Новосибирск", "Кемерово"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "event-theater-trip-1",
    fromCity: "Барнаул",
    toCity: "Красноярск",
    date: "2026-07-27",
    departureTime: "06:40",
    arrivalTime: "17:55",
    driver: mockUsers[0],
    pricePerSeat: 2500,
    freeSeats: 3,
    type: "passenger",
    stops: ["Новосибирск", "Кемерово", "Мариинск"],
    carId: "car-u1",
    amenities: {
      childSeat: true,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
  },
  {
    id: "event-theater-trip-2",
    fromCity: "Барнаул",
    toCity: "Красноярск",
    date: "2026-07-27",
    departureTime: "09:00",
    arrivalTime: "20:20",
    driver: mockUsers[3],
    pricePerSeat: 2700,
    freeSeats: 4,
    type: "passenger",
    stops: ["Новосибирск", "Ачинск"],
    carId: "car-u4",
    amenities: {
      childSeat: true,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
  },
  {
    id: "event-hockey-trip-1",
    fromCity: "Барнаул",
    toCity: "Новосибирск",
    date: "2026-07-28",
    departureTime: "13:10",
    arrivalTime: "17:25",
    driver: mockUsers[1],
    pricePerSeat: 1000,
    freeSeats: 2,
    type: "passenger",
    stops: ["Новоалтайск", "Тальменка"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
  },
  {
    id: "event-hockey-trip-2",
    fromCity: "Барнаул",
    toCity: "Новосибирск",
    date: "2026-07-28",
    departureTime: "14:00",
    arrivalTime: "18:05",
    driver: mockUsers[0],
    pricePerSeat: 1100,
    freeSeats: 3,
    type: "passenger",
    stops: ["Тальменка", "Черепаново"],
    carId: "car-u1",
    amenities: {
      childSeat: true,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
  },
  {
    id: "cargo-1",
    fromCity: "Барнаул",
    toCity: "Новосибирск",
    date: "2026-07-05",
    departureTime: "10:00",
    arrivalTime: "14:30",
    driver: mockUsers[2],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Тальменка"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["мебель", "личные вещи"],
    cargoLength: 2.1,
    cargoHeight: 1.8,
    cargoWidth: 1.1,
    cargoWeight: 100,
    cargoVehicleType: "фургон",
    cargoServices: ["помощь с погрузкой", "крепление груза"],
    pricePerCar: 8500,
  },
  {
    id: "cargo-2",
    fromCity: "Барнаул",
    toCity: "Бийск",
    date: "2026-07-06",
    departureTime: "11:20",
    arrivalTime: "14:40",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Зональное"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["техника"],
    cargoLength: 1.7,
    cargoHeight: 1.9,
    cargoWidth: 0.8,
    cargoWeight: 100,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["помощь с разгрузкой", "доставка до двери"],
    pricePerCar: 6000,
  },
  {
    id: "cargo-3",
    fromCity: "Новосибирск",
    toCity: "Барнаул",
    date: "2026-07-09",
    departureTime: "09:00",
    arrivalTime: "13:20",
    driver: mockUsers[0],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    carId: "car-u1",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
    cargoTypes: ["документы", "посылка"],
    cargoLength: 0.4,
    cargoHeight: 0.2,
    cargoWidth: 0.3,
    cargoWeight: 10,
    cargoVehicleType: "легковой автомобиль",
    cargoServices: ["доставка до двери", "фотоотчёт"],
    pricePerCar: 4500,
  },
  {
    id: "cargo-4",
    fromCity: "Барнаул",
    toCity: "Кемерово",
    date: "2026-07-11",
    departureTime: "06:45",
    arrivalTime: "13:50",
    driver: mockUsers[3],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Новосибирск"],
    carId: "car-u4",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
    cargoTypes: ["личные вещи"],
    cargoLength: 1.2,
    cargoHeight: 0.8,
    cargoWidth: 0.7,
    cargoWeight: 50,
    cargoVehicleType: "универсал",
    cargoServices: ["помощь с погрузкой"],
    pricePerCar: 7200,
  },
  {
    id: "cargo-5",
    fromCity: "Горно-Алтайск",
    toCity: "Барнаул",
    date: "2026-07-13",
    departureTime: "15:30",
    arrivalTime: "20:00",
    driver: mockUsers[1],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Бийск"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
    cargoTypes: ["посылка", "хрупкий груз"],
    cargoLength: 0.9,
    cargoHeight: 0.6,
    cargoWidth: 0.5,
    cargoWeight: 80,
    cargoVehicleType: "минивэн",
    cargoServices: ["фотоотчёт"],
    pricePerCar: 3500,
  },
  {
    id: "passenger-nsk-1",
    fromCity: "Барнаул",
    toCity: "Новосибирск",
    date: "2026-07-15",
    departureTime: "06:40",
    arrivalTime: "10:55",
    driver: mockUsers[0],
    pricePerSeat: 950,
    freeSeats: 3,
    type: "passenger",
    stops: ["Новоалтайск", "Тальменка", "Черепаново"],
    carId: "car-u1",
    amenities: {
      childSeat: true,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
  },
  {
    id: "passenger-nsk-2",
    fromCity: "Новосибирск",
    toCity: "Барнаул",
    date: "2026-07-16",
    departureTime: "17:30",
    arrivalTime: "21:45",
    driver: mockUsers[3],
    pricePerSeat: 1000,
    freeSeats: 4,
    type: "passenger",
    stops: ["Искитим", "Черепаново"],
    carId: "car-u4",
    amenities: {
      childSeat: true,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
  },
  {
    id: "passenger-nsk-3",
    fromCity: "Бийск",
    toCity: "Новосибирск",
    date: "2026-07-18",
    departureTime: "08:10",
    arrivalTime: "14:25",
    driver: mockUsers[1],
    pricePerSeat: 1450,
    freeSeats: 2,
    type: "passenger",
    stops: ["Барнаул", "Тальменка"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
  },
  {
    id: "passenger-nsk-4",
    fromCity: "Новосибирск",
    toCity: "Камень-на-Оби",
    date: "2026-07-20",
    departureTime: "09:00",
    arrivalTime: "13:10",
    driver: mockUsers[2],
    pricePerSeat: 1200,
    freeSeats: 6,
    type: "passenger",
    stops: ["Ордынское", "Крутиха"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-nsk-5",
    fromCity: "Рубцовск",
    toCity: "Новосибирск",
    date: "2026-07-22",
    departureTime: "05:50",
    arrivalTime: "14:30",
    driver: mockUsers[4],
    pricePerSeat: 2200,
    freeSeats: 5,
    type: "passenger",
    stops: ["Алейск", "Барнаул", "Черепаново"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-biysk-1",
    fromCity: "Барнаул",
    toCity: "Бийск",
    date: "2026-07-15",
    departureTime: "09:20",
    arrivalTime: "12:10",
    driver: mockUsers[1],
    pricePerSeat: 700,
    freeSeats: 2,
    type: "passenger",
    stops: ["Новоалтайск", "Зональное"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
  },
  {
    id: "passenger-biysk-2",
    fromCity: "Бийск",
    toCity: "Барнаул",
    date: "2026-07-17",
    departureTime: "18:00",
    arrivalTime: "20:50",
    driver: mockUsers[4],
    pricePerSeat: 680,
    freeSeats: 4,
    type: "passenger",
    stops: ["Зональное"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-biysk-3",
    fromCity: "Бийск",
    toCity: "Горно-Алтайск",
    date: "2026-07-19",
    departureTime: "07:45",
    arrivalTime: "10:15",
    driver: mockUsers[3],
    pricePerSeat: 850,
    freeSeats: 3,
    type: "passenger",
    stops: ["Сростки", "Майма"],
    carId: "car-u4",
    amenities: {
      childSeat: true,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
  },
  {
    id: "passenger-biysk-4",
    fromCity: "Новосибирск",
    toCity: "Бийск",
    date: "2026-07-21",
    departureTime: "06:30",
    arrivalTime: "12:45",
    driver: mockUsers[2],
    pricePerSeat: 1500,
    freeSeats: 7,
    type: "passenger",
    stops: ["Черепаново", "Барнаул"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-biysk-5",
    fromCity: "Бийск",
    toCity: "Белокуриха",
    date: "2026-07-24",
    departureTime: "10:40",
    arrivalTime: "12:10",
    driver: mockUsers[0],
    pricePerSeat: 500,
    freeSeats: 1,
    type: "passenger",
    stops: ["Смоленское"],
    carId: "car-u1",
    amenities: {
      childSeat: true,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
  },
  {
    id: "passenger-kamen-1",
    fromCity: "Барнаул",
    toCity: "Камень-на-Оби",
    date: "2026-07-16",
    departureTime: "08:30",
    arrivalTime: "12:20",
    driver: mockUsers[3],
    pricePerSeat: 900,
    freeSeats: 3,
    type: "passenger",
    stops: ["Павловск", "Шелаболиха"],
    carId: "car-u4",
    amenities: {
      childSeat: true,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
  },
  {
    id: "passenger-kamen-2",
    fromCity: "Камень-на-Оби",
    toCity: "Барнаул",
    date: "2026-07-18",
    departureTime: "16:10",
    arrivalTime: "20:00",
    driver: mockUsers[0],
    pricePerSeat: 880,
    freeSeats: 2,
    type: "passenger",
    stops: ["Крутиха", "Павловск"],
    carId: "car-u1",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "small",
  },
  {
    id: "passenger-kamen-3",
    fromCity: "Новосибирск",
    toCity: "Камень-на-Оби",
    date: "2026-07-20",
    departureTime: "12:30",
    arrivalTime: "16:35",
    driver: mockUsers[2],
    pricePerSeat: 1250,
    freeSeats: 8,
    type: "passenger",
    stops: ["Ордынское", "Крутиха"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-kamen-4",
    fromCity: "Камень-на-Оби",
    toCity: "Новосибирск",
    date: "2026-07-23",
    departureTime: "07:20",
    arrivalTime: "11:40",
    driver: mockUsers[1],
    pricePerSeat: 1200,
    freeSeats: 4,
    type: "passenger",
    stops: ["Крутиха", "Ордынское"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
  },
  {
    id: "passenger-kamen-5",
    fromCity: "Камень-на-Оби",
    toCity: "Славгород",
    date: "2026-07-25",
    departureTime: "09:50",
    arrivalTime: "13:30",
    driver: mockUsers[4],
    pricePerSeat: 950,
    freeSeats: 5,
    type: "passenger",
    stops: ["Баево", "Хабары"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-rubtsovsk-1",
    fromCity: "Барнаул",
    toCity: "Рубцовск",
    date: "2026-07-17",
    departureTime: "07:10",
    arrivalTime: "11:45",
    driver: mockUsers[0],
    pricePerSeat: 1150,
    freeSeats: 3,
    type: "passenger",
    stops: ["Алейск", "Поспелиха"],
    carId: "car-u1",
    amenities: {
      childSeat: true,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
  },
  {
    id: "passenger-rubtsovsk-2",
    fromCity: "Рубцовск",
    toCity: "Барнаул",
    date: "2026-07-19",
    departureTime: "15:40",
    arrivalTime: "20:10",
    driver: mockUsers[3],
    pricePerSeat: 1180,
    freeSeats: 2,
    type: "passenger",
    stops: ["Поспелиха", "Алейск"],
    carId: "car-u4",
    amenities: {
      childSeat: true,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
  },
  {
    id: "passenger-rubtsovsk-3",
    fromCity: "Рубцовск",
    toCity: "Змеиногорск",
    date: "2026-07-21",
    departureTime: "08:00",
    arrivalTime: "10:05",
    driver: mockUsers[4],
    pricePerSeat: 550,
    freeSeats: 6,
    type: "passenger",
    stops: ["Горняк"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-rubtsovsk-4",
    fromCity: "Новосибирск",
    toCity: "Рубцовск",
    date: "2026-07-24",
    departureTime: "06:00",
    arrivalTime: "14:40",
    driver: mockUsers[2],
    pricePerSeat: 2300,
    freeSeats: 8,
    type: "passenger",
    stops: ["Барнаул", "Алейск"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-rubtsovsk-5",
    fromCity: "Рубцовск",
    toCity: "Бийск",
    date: "2026-07-26",
    departureTime: "09:30",
    arrivalTime: "15:20",
    driver: mockUsers[1],
    pricePerSeat: 1450,
    freeSeats: 1,
    type: "passenger",
    stops: ["Алейск", "Барнаул"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
  },
  {
    id: "cargo-nsk-1",
    fromCity: "Барнаул",
    toCity: "Новосибирск",
    date: "2026-07-15",
    departureTime: "11:00",
    arrivalTime: "15:30",
    driver: mockUsers[2],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Тальменка", "Черепаново"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["мебель", "личные вещи"],
    cargoLength: 2.4,
    cargoHeight: 1.6,
    cargoWidth: 1.2,
    cargoWeight: 320,
    cargoVehicleType: "фургон",
    cargoServices: ["помощь с погрузкой", "крепление груза"],
    pricePerCar: 9000,
  },
  {
    id: "cargo-nsk-2",
    fromCity: "Новосибирск",
    toCity: "Барнаул",
    date: "2026-07-16",
    departureTime: "08:30",
    arrivalTime: "13:00",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Искитим", "Черепаново"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["стройматериалы"],
    cargoLength: 3,
    cargoHeight: 1.8,
    cargoWidth: 1.5,
    cargoWeight: 850,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["помощь с разгрузкой", "доставка до двери"],
    pricePerCar: 11500,
  },
  {
    id: "cargo-nsk-3",
    fromCity: "Бийск",
    toCity: "Новосибирск",
    date: "2026-07-19",
    departureTime: "07:00",
    arrivalTime: "13:40",
    driver: mockUsers[0],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Барнаул", "Тальменка"],
    carId: "car-u1",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
    cargoTypes: ["посылка", "техника"],
    cargoLength: 1.1,
    cargoHeight: 0.8,
    cargoWidth: 0.7,
    cargoWeight: 90,
    cargoVehicleType: "легковой автомобиль",
    cargoServices: ["доставка до двери", "фотоотчёт"],
    pricePerCar: 5200,
  },
  {
    id: "cargo-nsk-4",
    fromCity: "Новосибирск",
    toCity: "Камень-на-Оби",
    date: "2026-07-22",
    departureTime: "10:15",
    arrivalTime: "14:20",
    driver: mockUsers[3],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Ордынское", "Крутиха"],
    carId: "car-u4",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
    cargoTypes: ["документы", "посылка"],
    cargoLength: 0.6,
    cargoHeight: 0.4,
    cargoWidth: 0.4,
    cargoWeight: 25,
    cargoVehicleType: "универсал",
    cargoServices: ["фотоотчёт"],
    pricePerCar: 4800,
  },
  {
    id: "cargo-nsk-5",
    fromCity: "Рубцовск",
    toCity: "Новосибирск",
    date: "2026-07-25",
    departureTime: "06:20",
    arrivalTime: "15:10",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Алейск", "Барнаул", "Черепаново"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["личные вещи", "мебель"],
    cargoLength: 2.8,
    cargoHeight: 1.9,
    cargoWidth: 1.6,
    cargoWeight: 700,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["помощь с погрузкой", "помощь с разгрузкой"],
    pricePerCar: 16800,
  },
  {
    id: "cargo-biysk-1",
    fromCity: "Барнаул",
    toCity: "Бийск",
    date: "2026-07-16",
    departureTime: "13:00",
    arrivalTime: "16:00",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Зональное"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["стройматериалы", "другое"],
    cargoLength: 2.2,
    cargoHeight: 1.5,
    cargoWidth: 1.3,
    cargoWeight: 500,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["крепление груза"],
    pricePerCar: 6800,
  },
  {
    id: "cargo-biysk-2",
    fromCity: "Бийск",
    toCity: "Барнаул",
    date: "2026-07-18",
    departureTime: "09:40",
    arrivalTime: "12:45",
    driver: mockUsers[2],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Зональное", "Новоалтайск"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["мебель"],
    cargoLength: 2,
    cargoHeight: 1.4,
    cargoWidth: 1,
    cargoWeight: 280,
    cargoVehicleType: "фургон",
    cargoServices: ["помощь с погрузкой", "доставка до двери"],
    pricePerCar: 6500,
  },
  {
    id: "cargo-biysk-3",
    fromCity: "Бийск",
    toCity: "Горно-Алтайск",
    date: "2026-07-20",
    departureTime: "08:20",
    arrivalTime: "11:00",
    driver: mockUsers[1],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Сростки", "Майма"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
    cargoTypes: ["посылка", "хрупкий груз"],
    cargoLength: 0.8,
    cargoHeight: 0.5,
    cargoWidth: 0.5,
    cargoWeight: 35,
    cargoVehicleType: "минивэн",
    cargoServices: ["фотоотчёт", "доставка до двери"],
    pricePerCar: 3600,
  },
  {
    id: "cargo-biysk-4",
    fromCity: "Новосибирск",
    toCity: "Бийск",
    date: "2026-07-23",
    departureTime: "06:50",
    arrivalTime: "13:15",
    driver: mockUsers[3],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Черепаново", "Барнаул"],
    carId: "car-u4",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
    cargoTypes: ["техника", "личные вещи"],
    cargoLength: 1.5,
    cargoHeight: 1,
    cargoWidth: 0.8,
    cargoWeight: 130,
    cargoVehicleType: "универсал",
    cargoServices: ["крепление груза", "фотоотчёт"],
    pricePerCar: 7600,
  },
  {
    id: "cargo-biysk-5",
    fromCity: "Бийск",
    toCity: "Белокуриха",
    date: "2026-07-26",
    departureTime: "12:10",
    arrivalTime: "13:50",
    driver: mockUsers[0],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Смоленское"],
    carId: "car-u1",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
    cargoTypes: ["документы", "посылка"],
    cargoLength: 0.5,
    cargoHeight: 0.3,
    cargoWidth: 0.3,
    cargoWeight: 15,
    cargoVehicleType: "легковой автомобиль",
    cargoServices: ["доставка до двери"],
    pricePerCar: 2400,
  },
  {
    id: "cargo-kamen-1",
    fromCity: "Барнаул",
    toCity: "Камень-на-Оби",
    date: "2026-07-17",
    departureTime: "10:30",
    arrivalTime: "14:20",
    driver: mockUsers[2],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Павловск", "Шелаболиха"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["стройматериалы"],
    cargoLength: 2.6,
    cargoHeight: 1.4,
    cargoWidth: 1.3,
    cargoWeight: 600,
    cargoVehicleType: "фургон",
    cargoServices: ["крепление груза", "помощь с разгрузкой"],
    pricePerCar: 8200,
  },
  {
    id: "cargo-kamen-2",
    fromCity: "Камень-на-Оби",
    toCity: "Барнаул",
    date: "2026-07-19",
    departureTime: "15:00",
    arrivalTime: "18:50",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Крутиха", "Павловск"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["личные вещи", "мебель"],
    cargoLength: 2.3,
    cargoHeight: 1.7,
    cargoWidth: 1.4,
    cargoWeight: 450,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["помощь с погрузкой", "доставка до двери"],
    pricePerCar: 8700,
  },
  {
    id: "cargo-kamen-3",
    fromCity: "Новосибирск",
    toCity: "Камень-на-Оби",
    date: "2026-07-21",
    departureTime: "08:45",
    arrivalTime: "12:55",
    driver: mockUsers[1],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Ордынское", "Крутиха"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
    cargoTypes: ["документы", "хрупкий груз"],
    cargoLength: 0.7,
    cargoHeight: 0.5,
    cargoWidth: 0.4,
    cargoWeight: 20,
    cargoVehicleType: "минивэн",
    cargoServices: ["фотоотчёт"],
    pricePerCar: 4200,
  },
  {
    id: "cargo-kamen-4",
    fromCity: "Камень-на-Оби",
    toCity: "Новосибирск",
    date: "2026-07-24",
    departureTime: "07:30",
    arrivalTime: "11:50",
    driver: mockUsers[3],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Крутиха", "Ордынское"],
    carId: "car-u4",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
    cargoTypes: ["техника", "посылка"],
    cargoLength: 1.2,
    cargoHeight: 0.9,
    cargoWidth: 0.7,
    cargoWeight: 85,
    cargoVehicleType: "универсал",
    cargoServices: ["крепление груза", "доставка до двери"],
    pricePerCar: 5200,
  },
  {
    id: "cargo-kamen-5",
    fromCity: "Камень-на-Оби",
    toCity: "Славгород",
    date: "2026-07-27",
    departureTime: "09:10",
    arrivalTime: "12:55",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Баево", "Хабары"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["стройматериалы", "другое"],
    cargoLength: 3,
    cargoHeight: 1.7,
    cargoWidth: 1.5,
    cargoWeight: 900,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["крепление груза"],
    pricePerCar: 10800,
  },
  {
    id: "cargo-rubtsovsk-1",
    fromCity: "Барнаул",
    toCity: "Рубцовск",
    date: "2026-07-18",
    departureTime: "09:00",
    arrivalTime: "13:40",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Алейск", "Поспелиха"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["мебель", "личные вещи"],
    cargoLength: 2.7,
    cargoHeight: 1.8,
    cargoWidth: 1.5,
    cargoWeight: 650,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["помощь с погрузкой", "крепление груза"],
    pricePerCar: 11200,
  },
  {
    id: "cargo-rubtsovsk-2",
    fromCity: "Рубцовск",
    toCity: "Барнаул",
    date: "2026-07-20",
    departureTime: "14:20",
    arrivalTime: "19:00",
    driver: mockUsers[2],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Поспелиха", "Алейск"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["техника"],
    cargoLength: 1.6,
    cargoHeight: 1.2,
    cargoWidth: 0.9,
    cargoWeight: 180,
    cargoVehicleType: "фургон",
    cargoServices: ["помощь с разгрузкой", "фотоотчёт"],
    pricePerCar: 9600,
  },
  {
    id: "cargo-rubtsovsk-3",
    fromCity: "Рубцовск",
    toCity: "Змеиногорск",
    date: "2026-07-22",
    departureTime: "08:40",
    arrivalTime: "10:45",
    driver: mockUsers[0],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Горняк"],
    carId: "car-u1",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
    cargoTypes: ["посылка", "документы"],
    cargoLength: 0.6,
    cargoHeight: 0.4,
    cargoWidth: 0.4,
    cargoWeight: 18,
    cargoVehicleType: "легковой автомобиль",
    cargoServices: ["доставка до двери"],
    pricePerCar: 2600,
  },
  {
    id: "cargo-rubtsovsk-4",
    fromCity: "Новосибирск",
    toCity: "Рубцовск",
    date: "2026-07-25",
    departureTime: "05:45",
    arrivalTime: "14:35",
    driver: mockUsers[3],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Барнаул", "Алейск"],
    carId: "car-u4",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
    cargoTypes: ["хрупкий груз", "личные вещи"],
    cargoLength: 1.4,
    cargoHeight: 1,
    cargoWidth: 0.8,
    cargoWeight: 120,
    cargoVehicleType: "универсал",
    cargoServices: ["крепление груза", "фотоотчёт"],
    pricePerCar: 13200,
  },
  {
    id: "cargo-rubtsovsk-5",
    fromCity: "Рубцовск",
    toCity: "Бийск",
    date: "2026-07-28",
    departureTime: "09:20",
    arrivalTime: "15:00",
    driver: mockUsers[1],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Алейск", "Барнаул"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
    cargoTypes: ["посылка", "животные / растения"],
    cargoLength: 0.9,
    cargoHeight: 0.7,
    cargoWidth: 0.6,
    cargoWeight: 45,
    cargoVehicleType: "минивэн",
    cargoServices: ["доставка до двери", "фотоотчёт"],
    pricePerCar: 6200,
  },
  {
    id: "passenger-barnaul-nsk-extra-1",
    fromCity: "Барнаул",
    toCity: "Новосибирск",
    date: "2026-07-29",
    departureTime: "07:25",
    arrivalTime: "11:35",
    driver: mockUsers[3],
    pricePerSeat: 980,
    freeSeats: 4,
    type: "passenger",
    stops: ["Новоалтайск", "Тальменка", "Черепаново"],
    carId: "car-u4",
    amenities: {
      childSeat: true,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
  },
  {
    id: "cargo-barnaul-nsk-extra-1",
    fromCity: "Барнаул",
    toCity: "Новосибирск",
    date: "2026-07-30",
    departureTime: "12:00",
    arrivalTime: "16:25",
    driver: mockUsers[2],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Тальменка", "Черепаново"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["техника", "посылка"],
    cargoLength: 1.4,
    cargoHeight: 1,
    cargoWidth: 0.8,
    cargoWeight: 120,
    cargoVehicleType: "фургон",
    cargoServices: ["крепление груза", "фотоотчёт"],
    pricePerCar: 8800,
  },
  {
    id: "passenger-barnaul-biysk-extra-1",
    fromCity: "Барнаул",
    toCity: "Бийск",
    date: "2026-07-29",
    departureTime: "10:15",
    arrivalTime: "13:05",
    driver: mockUsers[1],
    pricePerSeat: 720,
    freeSeats: 2,
    type: "passenger",
    stops: ["Новоалтайск", "Зональное"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
  },
  {
    id: "cargo-barnaul-biysk-extra-1",
    fromCity: "Барнаул",
    toCity: "Бийск",
    date: "2026-07-31",
    departureTime: "08:50",
    arrivalTime: "11:55",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Зональное"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["мебель", "личные вещи"],
    cargoLength: 2,
    cargoHeight: 1.5,
    cargoWidth: 1.2,
    cargoWeight: 360,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["помощь с погрузкой", "доставка до двери"],
    pricePerCar: 6900,
  },
  {
    id: "passenger-barnaul-kamen-extra-1",
    fromCity: "Барнаул",
    toCity: "Камень-на-Оби",
    date: "2026-07-30",
    departureTime: "09:35",
    arrivalTime: "13:25",
    driver: mockUsers[0],
    pricePerSeat: 920,
    freeSeats: 3,
    type: "passenger",
    stops: ["Павловск", "Шелаболиха"],
    carId: "car-u1",
    amenities: {
      childSeat: true,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
  },
  {
    id: "cargo-barnaul-kamen-extra-1",
    fromCity: "Барнаул",
    toCity: "Камень-на-Оби",
    date: "2026-08-01",
    departureTime: "11:10",
    arrivalTime: "15:05",
    driver: mockUsers[2],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Павловск", "Крутиха"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["стройматериалы", "другое"],
    cargoLength: 2.5,
    cargoHeight: 1.4,
    cargoWidth: 1.2,
    cargoWeight: 520,
    cargoVehicleType: "фургон",
    cargoServices: ["крепление груза"],
    pricePerCar: 8400,
  },
  {
    id: "passenger-barnaul-rubtsovsk-extra-1",
    fromCity: "Барнаул",
    toCity: "Рубцовск",
    date: "2026-07-31",
    departureTime: "06:55",
    arrivalTime: "11:30",
    driver: mockUsers[4],
    pricePerSeat: 1200,
    freeSeats: 5,
    type: "passenger",
    stops: ["Алейск", "Поспелиха"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "cargo-barnaul-rubtsovsk-extra-1",
    fromCity: "Барнаул",
    toCity: "Рубцовск",
    date: "2026-08-02",
    departureTime: "13:30",
    arrivalTime: "18:10",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Алейск", "Поспелиха"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["личные вещи", "техника"],
    cargoLength: 2.4,
    cargoHeight: 1.7,
    cargoWidth: 1.4,
    cargoWeight: 580,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["помощь с погрузкой", "крепление груза"],
    pricePerCar: 11600,
  },
];

export const mockBookings: Booking[] = [];

export const mockReviews: Review[] = [
  {
    id: "review-1",
    targetUserId: "u1",
    authorId: "u2",
    rating: 5,
    text: "Иван приехал заранее, помог с багажом и спокойно довез до места.",
    createdAt: "2026-04-20T10:00:00.000Z",
    tripId: "passenger-1",
  },
  {
    id: "review-2",
    targetUserId: "u1",
    authorId: "u4",
    rating: 5,
    text: "Комфортная поездка, чистая машина и понятная коммуникация по маршруту.",
    createdAt: "2026-05-02T15:30:00.000Z",
    tripId: "cargo-3",
  },
  {
    id: "review-3",
    targetUserId: "u2",
    authorId: "u1",
    rating: 5,
    text: "Анна быстро отвечает и аккуратно планирует остановки. Все прошло по договоренности.",
    createdAt: "2026-05-05T09:15:00.000Z",
    tripId: "passenger-2",
  },
  {
    id: "review-4",
    targetUserId: "u3",
    authorId: "u5",
    rating: 4,
    text: "Груз доставлен без повреждений, водитель был на связи на всем маршруте.",
    createdAt: "2026-05-10T12:45:00.000Z",
    tripId: "cargo-1",
  },
  {
    id: "review-5",
    targetUserId: "u4",
    authorId: "u2",
    rating: 5,
    text: "Мария очень пунктуальна, в машине чисто и спокойно.",
    createdAt: "2026-05-12T17:20:00.000Z",
    tripId: "passenger-3",
  },
  {
    id: "review-6",
    targetUserId: "u5",
    authorId: "u3",
    rating: 4,
    text: "Дмитрий помог с крупной техникой и заранее уточнил все детали перевозки.",
    createdAt: "2026-05-18T08:10:00.000Z",
    tripId: "cargo-2",
  },
];

export const mockChats: Chat[] = [];

export const mockChatMessages: ChatMessage[] = [];
  {
    id: "u4",
    fullName: "Мария Волкова",
    email: "maria.volkova@example.com",
    rating: 5,
    carName: "Hyundai Solaris, синий",
    about:
      "Пунктуальный водитель, заранее предупреждаю об остановках и изменениях по времени.",
    location: "Барнаул",
  },
  {
    id: "u5",
    fullName: "Дмитрий Соколов",
    email: "dmitry.sokolov@example.com",
    rating: 4.6,
    carName: "ГАЗель Next, белый",
    about:
      "Работаю с грузовыми поездками по Алтайскому краю, могу помочь с погрузкой по договоренности.",
    location: "Бийск",
  },
];

export const mockCars: Car[] = [
  {
    id: "car-u1",
    ownerId: "u1",
    brand: "Toyota",
    model: "Camry",
    color: "черный",
    plate: "А123ВС22",
  },
  {
    id: "car-u2",
    ownerId: "u2",
    brand: "Kia",
    model: "Rio",
    color: "белый",
    plate: "В456ОР22",
  },
  {
    id: "car-u3",
    ownerId: "u3",
    brand: "Volkswagen",
    model: "Transporter",
    color: "серый",
    plate: "Е789КХ22",
  },
  {
    id: "car-u4",
    ownerId: "u4",
    brand: "Hyundai",
    model: "Solaris",
    color: "синий",
    plate: "М234ТТ22",
  },
  {
    id: "car-u5",
    ownerId: "u5",
    brand: "ГАЗель",
    model: "Next",
    color: "белый",
    plate: "Н567РУ22",
  },
];

export const mockTrips: Trip[] = [
  {
    id: "passenger-1",
    fromCity: "Барнаул",
    toCity: "Новосибирск",
    date: "2026-07-05",
    departureTime: "08:00",
    arrivalTime: "12:10",
    driver: mockUsers[0],
    pricePerSeat: 900,
    freeSeats: 3,
    type: "passenger",
    stops: ["Тальменка", "Черепаново"],
    carId: "car-u1",
    amenities: {
      childSeat: true,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
  },
  {
    id: "passenger-2",
    fromCity: "Барнаул",
    toCity: "Горно-Алтайск",
    date: "2026-07-07",
    departureTime: "07:30",
    arrivalTime: "12:20",
    driver: mockUsers[1],
    pricePerSeat: 1600,
    freeSeats: 2,
    type: "passenger",
    stops: ["Бийск", "Сростки"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
  },
  {
    id: "passenger-3",
    fromCity: "Новосибирск",
    toCity: "Барнаул",
    date: "2026-07-08",
    departureTime: "18:20",
    arrivalTime: "22:30",
    driver: mockUsers[3],
    pricePerSeat: 950,
    freeSeats: 4,
    type: "passenger",
    stops: ["Искитим"],
    carId: "car-u4",
    amenities: {
      childSeat: true,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
  },
  {
    id: "passenger-4",
    fromCity: "Барнаул",
    toCity: "Кемерово",
    date: "2026-07-10",
    departureTime: "09:15",
    arrivalTime: "16:05",
    driver: mockUsers[2],
    pricePerSeat: 1800,
    freeSeats: 2,
    type: "passenger",
    stops: ["Новосибирск", "Ленинск-Кузнецкий"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-5",
    fromCity: "Бийск",
    toCity: "Барнаул",
    date: "2026-07-12",
    departureTime: "14:00",
    arrivalTime: "17:10",
    driver: mockUsers[4],
    pricePerSeat: 700,
    freeSeats: 3,
    type: "passenger",
    stops: ["Зональное"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "cargo-1",
    fromCity: "Барнаул",
    toCity: "Новосибирск",
    date: "2026-07-05",
    departureTime: "10:00",
    arrivalTime: "14:30",
    driver: mockUsers[2],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Тальменка"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["мебель", "личные вещи"],
    cargoLength: 2.1,
    cargoHeight: 1.8,
    cargoWidth: 1.1,
    cargoWeight: 100,
    cargoVehicleType: "фургон",
    cargoServices: ["помощь с погрузкой", "крепление груза"],
    pricePerCar: 8500,
  },
  {
    id: "cargo-2",
    fromCity: "Барнаул",
    toCity: "Бийск",
    date: "2026-07-06",
    departureTime: "11:20",
    arrivalTime: "14:40",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Зональное"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["техника"],
    cargoLength: 1.7,
    cargoHeight: 1.9,
    cargoWidth: 0.8,
    cargoWeight: 100,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["помощь с разгрузкой", "доставка до двери"],
    pricePerCar: 6000,
  },
  {
    id: "cargo-3",
    fromCity: "Новосибирск",
    toCity: "Барнаул",
    date: "2026-07-09",
    departureTime: "09:00",
    arrivalTime: "13:20",
    driver: mockUsers[0],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    carId: "car-u1",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
    cargoTypes: ["документы", "посылка"],
    cargoLength: 0.4,
    cargoHeight: 0.2,
    cargoWidth: 0.3,
    cargoWeight: 10,
    cargoVehicleType: "легковой автомобиль",
    cargoServices: ["доставка до двери", "фотоотчёт"],
    pricePerCar: 4500,
  },
  {
    id: "cargo-4",
    fromCity: "Барнаул",
    toCity: "Кемерово",
    date: "2026-07-11",
    departureTime: "06:45",
    arrivalTime: "13:50",
    driver: mockUsers[3],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Новосибирск"],
    carId: "car-u4",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
    cargoTypes: ["личные вещи"],
    cargoLength: 1.2,
    cargoHeight: 0.8,
    cargoWidth: 0.7,
    cargoWeight: 50,
    cargoVehicleType: "универсал",
    cargoServices: ["помощь с погрузкой"],
    pricePerCar: 7200,
  },
  {
    id: "cargo-5",
    fromCity: "Горно-Алтайск",
    toCity: "Барнаул",
    date: "2026-07-13",
    departureTime: "15:30",
    arrivalTime: "20:00",
    driver: mockUsers[1],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Бийск"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
    cargoTypes: ["посылка", "хрупкий груз"],
    cargoLength: 0.9,
    cargoHeight: 0.6,
    cargoWidth: 0.5,
    cargoWeight: 80,
    cargoVehicleType: "минивэн",
    cargoServices: ["фотоотчёт"],
    pricePerCar: 3500,
  },
  {
    id: "passenger-nsk-1",
    fromCity: "Барнаул",
    toCity: "Новосибирск",
    date: "2026-07-15",
    departureTime: "06:40",
    arrivalTime: "10:55",
    driver: mockUsers[0],
    pricePerSeat: 950,
    freeSeats: 3,
    type: "passenger",
    stops: ["Новоалтайск", "Тальменка", "Черепаново"],
    carId: "car-u1",
    amenities: {
      childSeat: true,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
  },
  {
    id: "passenger-nsk-2",
    fromCity: "Новосибирск",
    toCity: "Барнаул",
    date: "2026-07-16",
    departureTime: "17:30",
    arrivalTime: "21:45",
    driver: mockUsers[3],
    pricePerSeat: 1000,
    freeSeats: 4,
    type: "passenger",
    stops: ["Искитим", "Черепаново"],
    carId: "car-u4",
    amenities: {
      childSeat: true,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
  },
  {
    id: "passenger-nsk-3",
    fromCity: "Бийск",
    toCity: "Новосибирск",
    date: "2026-07-18",
    departureTime: "08:10",
    arrivalTime: "14:25",
    driver: mockUsers[1],
    pricePerSeat: 1450,
    freeSeats: 2,
    type: "passenger",
    stops: ["Барнаул", "Тальменка"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
  },
  {
    id: "passenger-nsk-4",
    fromCity: "Новосибирск",
    toCity: "Камень-на-Оби",
    date: "2026-07-20",
    departureTime: "09:00",
    arrivalTime: "13:10",
    driver: mockUsers[2],
    pricePerSeat: 1200,
    freeSeats: 6,
    type: "passenger",
    stops: ["Ордынское", "Крутиха"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-nsk-5",
    fromCity: "Рубцовск",
    toCity: "Новосибирск",
    date: "2026-07-22",
    departureTime: "05:50",
    arrivalTime: "14:30",
    driver: mockUsers[4],
    pricePerSeat: 2200,
    freeSeats: 5,
    type: "passenger",
    stops: ["Алейск", "Барнаул", "Черепаново"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-biysk-1",
    fromCity: "Барнаул",
    toCity: "Бийск",
    date: "2026-07-15",
    departureTime: "09:20",
    arrivalTime: "12:10",
    driver: mockUsers[1],
    pricePerSeat: 700,
    freeSeats: 2,
    type: "passenger",
    stops: ["Новоалтайск", "Зональное"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
  },
  {
    id: "passenger-biysk-2",
    fromCity: "Бийск",
    toCity: "Барнаул",
    date: "2026-07-17",
    departureTime: "18:00",
    arrivalTime: "20:50",
    driver: mockUsers[4],
    pricePerSeat: 680,
    freeSeats: 4,
    type: "passenger",
    stops: ["Зональное"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-biysk-3",
    fromCity: "Бийск",
    toCity: "Горно-Алтайск",
    date: "2026-07-19",
    departureTime: "07:45",
    arrivalTime: "10:15",
    driver: mockUsers[3],
    pricePerSeat: 850,
    freeSeats: 3,
    type: "passenger",
    stops: ["Сростки", "Майма"],
    carId: "car-u4",
    amenities: {
      childSeat: true,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
  },
  {
    id: "passenger-biysk-4",
    fromCity: "Новосибирск",
    toCity: "Бийск",
    date: "2026-07-21",
    departureTime: "06:30",
    arrivalTime: "12:45",
    driver: mockUsers[2],
    pricePerSeat: 1500,
    freeSeats: 7,
    type: "passenger",
    stops: ["Черепаново", "Барнаул"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-biysk-5",
    fromCity: "Бийск",
    toCity: "Белокуриха",
    date: "2026-07-24",
    departureTime: "10:40",
    arrivalTime: "12:10",
    driver: mockUsers[0],
    pricePerSeat: 500,
    freeSeats: 1,
    type: "passenger",
    stops: ["Смоленское"],
    carId: "car-u1",
    amenities: {
      childSeat: true,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
  },
  {
    id: "passenger-kamen-1",
    fromCity: "Барнаул",
    toCity: "Камень-на-Оби",
    date: "2026-07-16",
    departureTime: "08:30",
    arrivalTime: "12:20",
    driver: mockUsers[3],
    pricePerSeat: 900,
    freeSeats: 3,
    type: "passenger",
    stops: ["Павловск", "Шелаболиха"],
    carId: "car-u4",
    amenities: {
      childSeat: true,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
  },
  {
    id: "passenger-kamen-2",
    fromCity: "Камень-на-Оби",
    toCity: "Барнаул",
    date: "2026-07-18",
    departureTime: "16:10",
    arrivalTime: "20:00",
    driver: mockUsers[0],
    pricePerSeat: 880,
    freeSeats: 2,
    type: "passenger",
    stops: ["Крутиха", "Павловск"],
    carId: "car-u1",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "small",
  },
  {
    id: "passenger-kamen-3",
    fromCity: "Новосибирск",
    toCity: "Камень-на-Оби",
    date: "2026-07-20",
    departureTime: "12:30",
    arrivalTime: "16:35",
    driver: mockUsers[2],
    pricePerSeat: 1250,
    freeSeats: 8,
    type: "passenger",
    stops: ["Ордынское", "Крутиха"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-kamen-4",
    fromCity: "Камень-на-Оби",
    toCity: "Новосибирск",
    date: "2026-07-23",
    departureTime: "07:20",
    arrivalTime: "11:40",
    driver: mockUsers[1],
    pricePerSeat: 1200,
    freeSeats: 4,
    type: "passenger",
    stops: ["Крутиха", "Ордынское"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
  },
  {
    id: "passenger-kamen-5",
    fromCity: "Камень-на-Оби",
    toCity: "Славгород",
    date: "2026-07-25",
    departureTime: "09:50",
    arrivalTime: "13:30",
    driver: mockUsers[4],
    pricePerSeat: 950,
    freeSeats: 5,
    type: "passenger",
    stops: ["Баево", "Хабары"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-rubtsovsk-1",
    fromCity: "Барнаул",
    toCity: "Рубцовск",
    date: "2026-07-17",
    departureTime: "07:10",
    arrivalTime: "11:45",
    driver: mockUsers[0],
    pricePerSeat: 1150,
    freeSeats: 3,
    type: "passenger",
    stops: ["Алейск", "Поспелиха"],
    carId: "car-u1",
    amenities: {
      childSeat: true,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
  },
  {
    id: "passenger-rubtsovsk-2",
    fromCity: "Рубцовск",
    toCity: "Барнаул",
    date: "2026-07-19",
    departureTime: "15:40",
    arrivalTime: "20:10",
    driver: mockUsers[3],
    pricePerSeat: 1180,
    freeSeats: 2,
    type: "passenger",
    stops: ["Поспелиха", "Алейск"],
    carId: "car-u4",
    amenities: {
      childSeat: true,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
  },
  {
    id: "passenger-rubtsovsk-3",
    fromCity: "Рубцовск",
    toCity: "Змеиногорск",
    date: "2026-07-21",
    departureTime: "08:00",
    arrivalTime: "10:05",
    driver: mockUsers[4],
    pricePerSeat: 550,
    freeSeats: 6,
    type: "passenger",
    stops: ["Горняк"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-rubtsovsk-4",
    fromCity: "Новосибирск",
    toCity: "Рубцовск",
    date: "2026-07-24",
    departureTime: "06:00",
    arrivalTime: "14:40",
    driver: mockUsers[2],
    pricePerSeat: 2300,
    freeSeats: 8,
    type: "passenger",
    stops: ["Барнаул", "Алейск"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "passenger-rubtsovsk-5",
    fromCity: "Рубцовск",
    toCity: "Бийск",
    date: "2026-07-26",
    departureTime: "09:30",
    arrivalTime: "15:20",
    driver: mockUsers[1],
    pricePerSeat: 1450,
    freeSeats: 1,
    type: "passenger",
    stops: ["Алейск", "Барнаул"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
  },
  {
    id: "cargo-nsk-1",
    fromCity: "Барнаул",
    toCity: "Новосибирск",
    date: "2026-07-15",
    departureTime: "11:00",
    arrivalTime: "15:30",
    driver: mockUsers[2],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Тальменка", "Черепаново"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["мебель", "личные вещи"],
    cargoLength: 2.4,
    cargoHeight: 1.6,
    cargoWidth: 1.2,
    cargoWeight: 320,
    cargoVehicleType: "фургон",
    cargoServices: ["помощь с погрузкой", "крепление груза"],
    pricePerCar: 9000,
  },
  {
    id: "cargo-nsk-2",
    fromCity: "Новосибирск",
    toCity: "Барнаул",
    date: "2026-07-16",
    departureTime: "08:30",
    arrivalTime: "13:00",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Искитим", "Черепаново"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["стройматериалы"],
    cargoLength: 3,
    cargoHeight: 1.8,
    cargoWidth: 1.5,
    cargoWeight: 850,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["помощь с разгрузкой", "доставка до двери"],
    pricePerCar: 11500,
  },
  {
    id: "cargo-nsk-3",
    fromCity: "Бийск",
    toCity: "Новосибирск",
    date: "2026-07-19",
    departureTime: "07:00",
    arrivalTime: "13:40",
    driver: mockUsers[0],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Барнаул", "Тальменка"],
    carId: "car-u1",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
    cargoTypes: ["посылка", "техника"],
    cargoLength: 1.1,
    cargoHeight: 0.8,
    cargoWidth: 0.7,
    cargoWeight: 90,
    cargoVehicleType: "легковой автомобиль",
    cargoServices: ["доставка до двери", "фотоотчёт"],
    pricePerCar: 5200,
  },
  {
    id: "cargo-nsk-4",
    fromCity: "Новосибирск",
    toCity: "Камень-на-Оби",
    date: "2026-07-22",
    departureTime: "10:15",
    arrivalTime: "14:20",
    driver: mockUsers[3],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Ордынское", "Крутиха"],
    carId: "car-u4",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
    cargoTypes: ["документы", "посылка"],
    cargoLength: 0.6,
    cargoHeight: 0.4,
    cargoWidth: 0.4,
    cargoWeight: 25,
    cargoVehicleType: "универсал",
    cargoServices: ["фотоотчёт"],
    pricePerCar: 4800,
  },
  {
    id: "cargo-nsk-5",
    fromCity: "Рубцовск",
    toCity: "Новосибирск",
    date: "2026-07-25",
    departureTime: "06:20",
    arrivalTime: "15:10",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Алейск", "Барнаул", "Черепаново"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["личные вещи", "мебель"],
    cargoLength: 2.8,
    cargoHeight: 1.9,
    cargoWidth: 1.6,
    cargoWeight: 700,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["помощь с погрузкой", "помощь с разгрузкой"],
    pricePerCar: 16800,
  },
  {
    id: "cargo-biysk-1",
    fromCity: "Барнаул",
    toCity: "Бийск",
    date: "2026-07-16",
    departureTime: "13:00",
    arrivalTime: "16:00",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Зональное"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["стройматериалы", "другое"],
    cargoLength: 2.2,
    cargoHeight: 1.5,
    cargoWidth: 1.3,
    cargoWeight: 500,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["крепление груза"],
    pricePerCar: 6800,
  },
  {
    id: "cargo-biysk-2",
    fromCity: "Бийск",
    toCity: "Барнаул",
    date: "2026-07-18",
    departureTime: "09:40",
    arrivalTime: "12:45",
    driver: mockUsers[2],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Зональное", "Новоалтайск"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["мебель"],
    cargoLength: 2,
    cargoHeight: 1.4,
    cargoWidth: 1,
    cargoWeight: 280,
    cargoVehicleType: "фургон",
    cargoServices: ["помощь с погрузкой", "доставка до двери"],
    pricePerCar: 6500,
  },
  {
    id: "cargo-biysk-3",
    fromCity: "Бийск",
    toCity: "Горно-Алтайск",
    date: "2026-07-20",
    departureTime: "08:20",
    arrivalTime: "11:00",
    driver: mockUsers[1],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Сростки", "Майма"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
    cargoTypes: ["посылка", "хрупкий груз"],
    cargoLength: 0.8,
    cargoHeight: 0.5,
    cargoWidth: 0.5,
    cargoWeight: 35,
    cargoVehicleType: "минивэн",
    cargoServices: ["фотоотчёт", "доставка до двери"],
    pricePerCar: 3600,
  },
  {
    id: "cargo-biysk-4",
    fromCity: "Новосибирск",
    toCity: "Бийск",
    date: "2026-07-23",
    departureTime: "06:50",
    arrivalTime: "13:15",
    driver: mockUsers[3],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Черепаново", "Барнаул"],
    carId: "car-u4",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
    cargoTypes: ["техника", "личные вещи"],
    cargoLength: 1.5,
    cargoHeight: 1,
    cargoWidth: 0.8,
    cargoWeight: 130,
    cargoVehicleType: "универсал",
    cargoServices: ["крепление груза", "фотоотчёт"],
    pricePerCar: 7600,
  },
  {
    id: "cargo-biysk-5",
    fromCity: "Бийск",
    toCity: "Белокуриха",
    date: "2026-07-26",
    departureTime: "12:10",
    arrivalTime: "13:50",
    driver: mockUsers[0],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Смоленское"],
    carId: "car-u1",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
    cargoTypes: ["документы", "посылка"],
    cargoLength: 0.5,
    cargoHeight: 0.3,
    cargoWidth: 0.3,
    cargoWeight: 15,
    cargoVehicleType: "легковой автомобиль",
    cargoServices: ["доставка до двери"],
    pricePerCar: 2400,
  },
  {
    id: "cargo-kamen-1",
    fromCity: "Барнаул",
    toCity: "Камень-на-Оби",
    date: "2026-07-17",
    departureTime: "10:30",
    arrivalTime: "14:20",
    driver: mockUsers[2],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Павловск", "Шелаболиха"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["стройматериалы"],
    cargoLength: 2.6,
    cargoHeight: 1.4,
    cargoWidth: 1.3,
    cargoWeight: 600,
    cargoVehicleType: "фургон",
    cargoServices: ["крепление груза", "помощь с разгрузкой"],
    pricePerCar: 8200,
  },
  {
    id: "cargo-kamen-2",
    fromCity: "Камень-на-Оби",
    toCity: "Барнаул",
    date: "2026-07-19",
    departureTime: "15:00",
    arrivalTime: "18:50",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Крутиха", "Павловск"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["личные вещи", "мебель"],
    cargoLength: 2.3,
    cargoHeight: 1.7,
    cargoWidth: 1.4,
    cargoWeight: 450,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["помощь с погрузкой", "доставка до двери"],
    pricePerCar: 8700,
  },
  {
    id: "cargo-kamen-3",
    fromCity: "Новосибирск",
    toCity: "Камень-на-Оби",
    date: "2026-07-21",
    departureTime: "08:45",
    arrivalTime: "12:55",
    driver: mockUsers[1],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Ордынское", "Крутиха"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
    cargoTypes: ["документы", "хрупкий груз"],
    cargoLength: 0.7,
    cargoHeight: 0.5,
    cargoWidth: 0.4,
    cargoWeight: 20,
    cargoVehicleType: "минивэн",
    cargoServices: ["фотоотчёт"],
    pricePerCar: 4200,
  },
  {
    id: "cargo-kamen-4",
    fromCity: "Камень-на-Оби",
    toCity: "Новосибирск",
    date: "2026-07-24",
    departureTime: "07:30",
    arrivalTime: "11:50",
    driver: mockUsers[3],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Крутиха", "Ордынское"],
    carId: "car-u4",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
    cargoTypes: ["техника", "посылка"],
    cargoLength: 1.2,
    cargoHeight: 0.9,
    cargoWidth: 0.7,
    cargoWeight: 85,
    cargoVehicleType: "универсал",
    cargoServices: ["крепление груза", "доставка до двери"],
    pricePerCar: 5200,
  },
  {
    id: "cargo-kamen-5",
    fromCity: "Камень-на-Оби",
    toCity: "Славгород",
    date: "2026-07-27",
    departureTime: "09:10",
    arrivalTime: "12:55",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Баево", "Хабары"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["стройматериалы", "другое"],
    cargoLength: 3,
    cargoHeight: 1.7,
    cargoWidth: 1.5,
    cargoWeight: 900,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["крепление груза"],
    pricePerCar: 10800,
  },
  {
    id: "cargo-rubtsovsk-1",
    fromCity: "Барнаул",
    toCity: "Рубцовск",
    date: "2026-07-18",
    departureTime: "09:00",
    arrivalTime: "13:40",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Алейск", "Поспелиха"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["мебель", "личные вещи"],
    cargoLength: 2.7,
    cargoHeight: 1.8,
    cargoWidth: 1.5,
    cargoWeight: 650,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["помощь с погрузкой", "крепление груза"],
    pricePerCar: 11200,
  },
  {
    id: "cargo-rubtsovsk-2",
    fromCity: "Рубцовск",
    toCity: "Барнаул",
    date: "2026-07-20",
    departureTime: "14:20",
    arrivalTime: "19:00",
    driver: mockUsers[2],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Поспелиха", "Алейск"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["техника"],
    cargoLength: 1.6,
    cargoHeight: 1.2,
    cargoWidth: 0.9,
    cargoWeight: 180,
    cargoVehicleType: "фургон",
    cargoServices: ["помощь с разгрузкой", "фотоотчёт"],
    pricePerCar: 9600,
  },
  {
    id: "cargo-rubtsovsk-3",
    fromCity: "Рубцовск",
    toCity: "Змеиногорск",
    date: "2026-07-22",
    departureTime: "08:40",
    arrivalTime: "10:45",
    driver: mockUsers[0],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Горняк"],
    carId: "car-u1",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
    cargoTypes: ["посылка", "документы"],
    cargoLength: 0.6,
    cargoHeight: 0.4,
    cargoWidth: 0.4,
    cargoWeight: 18,
    cargoVehicleType: "легковой автомобиль",
    cargoServices: ["доставка до двери"],
    pricePerCar: 2600,
  },
  {
    id: "cargo-rubtsovsk-4",
    fromCity: "Новосибирск",
    toCity: "Рубцовск",
    date: "2026-07-25",
    departureTime: "05:45",
    arrivalTime: "14:35",
    driver: mockUsers[3],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Барнаул", "Алейск"],
    carId: "car-u4",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
    cargoTypes: ["хрупкий груз", "личные вещи"],
    cargoLength: 1.4,
    cargoHeight: 1,
    cargoWidth: 0.8,
    cargoWeight: 120,
    cargoVehicleType: "универсал",
    cargoServices: ["крепление груза", "фотоотчёт"],
    pricePerCar: 13200,
  },
  {
    id: "cargo-rubtsovsk-5",
    fromCity: "Рубцовск",
    toCity: "Бийск",
    date: "2026-07-28",
    departureTime: "09:20",
    arrivalTime: "15:00",
    driver: mockUsers[1],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Алейск", "Барнаул"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
    cargoTypes: ["посылка", "животные / растения"],
    cargoLength: 0.9,
    cargoHeight: 0.7,
    cargoWidth: 0.6,
    cargoWeight: 45,
    cargoVehicleType: "минивэн",
    cargoServices: ["доставка до двери", "фотоотчёт"],
    pricePerCar: 6200,
  },
  {
    id: "passenger-barnaul-nsk-extra-1",
    fromCity: "Барнаул",
    toCity: "Новосибирск",
    date: "2026-07-29",
    departureTime: "07:25",
    arrivalTime: "11:35",
    driver: mockUsers[3],
    pricePerSeat: 980,
    freeSeats: 4,
    type: "passenger",
    stops: ["Новоалтайск", "Тальменка", "Черепаново"],
    carId: "car-u4",
    amenities: {
      childSeat: true,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "medium",
  },
  {
    id: "cargo-barnaul-nsk-extra-1",
    fromCity: "Барнаул",
    toCity: "Новосибирск",
    date: "2026-07-30",
    departureTime: "12:00",
    arrivalTime: "16:25",
    driver: mockUsers[2],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Тальменка", "Черепаново"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["техника", "посылка"],
    cargoLength: 1.4,
    cargoHeight: 1,
    cargoWidth: 0.8,
    cargoWeight: 120,
    cargoVehicleType: "фургон",
    cargoServices: ["крепление груза", "фотоотчёт"],
    pricePerCar: 8800,
  },
  {
    id: "passenger-barnaul-biysk-extra-1",
    fromCity: "Барнаул",
    toCity: "Бийск",
    date: "2026-07-29",
    departureTime: "10:15",
    arrivalTime: "13:05",
    driver: mockUsers[1],
    pricePerSeat: 720,
    freeSeats: 2,
    type: "passenger",
    stops: ["Новоалтайск", "Зональное"],
    carId: "car-u2",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "female",
    baggageSize: "small",
  },
  {
    id: "cargo-barnaul-biysk-extra-1",
    fromCity: "Барнаул",
    toCity: "Бийск",
    date: "2026-07-31",
    departureTime: "08:50",
    arrivalTime: "11:55",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Зональное"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["мебель", "личные вещи"],
    cargoLength: 2,
    cargoHeight: 1.5,
    cargoWidth: 1.2,
    cargoWeight: 360,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["помощь с погрузкой", "доставка до двери"],
    pricePerCar: 6900,
  },
  {
    id: "passenger-barnaul-kamen-extra-1",
    fromCity: "Барнаул",
    toCity: "Камень-на-Оби",
    date: "2026-07-30",
    departureTime: "09:35",
    arrivalTime: "13:25",
    driver: mockUsers[0],
    pricePerSeat: 920,
    freeSeats: 3,
    type: "passenger",
    stops: ["Павловск", "Шелаболиха"],
    carId: "car-u1",
    amenities: {
      childSeat: true,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "medium",
  },
  {
    id: "cargo-barnaul-kamen-extra-1",
    fromCity: "Барнаул",
    toCity: "Камень-на-Оби",
    date: "2026-08-01",
    departureTime: "11:10",
    arrivalTime: "15:05",
    driver: mockUsers[2],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Павловск", "Крутиха"],
    carId: "car-u3",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["стройматериалы", "другое"],
    cargoLength: 2.5,
    cargoHeight: 1.4,
    cargoWidth: 1.2,
    cargoWeight: 520,
    cargoVehicleType: "фургон",
    cargoServices: ["крепление груза"],
    pricePerCar: 8400,
  },
  {
    id: "passenger-barnaul-rubtsovsk-extra-1",
    fromCity: "Барнаул",
    toCity: "Рубцовск",
    date: "2026-07-31",
    departureTime: "06:55",
    arrivalTime: "11:30",
    driver: mockUsers[4],
    pricePerSeat: 1200,
    freeSeats: 5,
    type: "passenger",
    stops: ["Алейск", "Поспелиха"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: true,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
  },
  {
    id: "cargo-barnaul-rubtsovsk-extra-1",
    fromCity: "Барнаул",
    toCity: "Рубцовск",
    date: "2026-08-02",
    departureTime: "13:30",
    arrivalTime: "18:10",
    driver: mockUsers[4],
    pricePerSeat: 0,
    freeSeats: 1,
    type: "cargo",
    stops: ["Алейск", "Поспелиха"],
    carId: "car-u5",
    amenities: {
      childSeat: false,
      petsAllowed: false,
      smokingAllowed: false,
      luggageAllowed: true,
    },
    driverGender: "male",
    baggageSize: "large",
    cargoTypes: ["личные вещи", "техника"],
    cargoLength: 2.4,
    cargoHeight: 1.7,
    cargoWidth: 1.4,
    cargoWeight: 580,
    cargoVehicleType: "газель / грузовой автомобиль",
    cargoServices: ["помощь с погрузкой", "крепление груза"],
    pricePerCar: 11600,
  },
];

export const mockBookings: Booking[] = [];

export const mockReviews: Review[] = [
  {
    id: "review-1",
    targetUserId: "u1",
    authorId: "u2",
    rating: 5,
    text: "Иван приехал заранее, помог с багажом и спокойно довез до места.",
    createdAt: "2026-04-20T10:00:00.000Z",
    tripId: "passenger-1",
  },
  {
    id: "review-2",
    targetUserId: "u1",
    authorId: "u4",
    rating: 5,
    text: "Комфортная поездка, чистая машина и понятная коммуникация по маршруту.",
    createdAt: "2026-05-02T15:30:00.000Z",
    tripId: "cargo-3",
  },
  {
    id: "review-3",
    targetUserId: "u2",
    authorId: "u1",
    rating: 5,
    text: "Анна быстро отвечает и аккуратно планирует остановки. Все прошло по договоренности.",
    createdAt: "2026-05-05T09:15:00.000Z",
    tripId: "passenger-2",
  },
  {
    id: "review-4",
    targetUserId: "u3",
    authorId: "u5",
    rating: 4,
    text: "Груз доставлен без повреждений, водитель был на связи на всем маршруте.",
    createdAt: "2026-05-10T12:45:00.000Z",
    tripId: "cargo-1",
  },
  {
    id: "review-5",
    targetUserId: "u4",
    authorId: "u2",
    rating: 5,
    text: "Мария очень пунктуальна, в машине чисто и спокойно.",
    createdAt: "2026-05-12T17:20:00.000Z",
    tripId: "passenger-3",
  },
  {
    id: "review-6",
    targetUserId: "u5",
    authorId: "u3",
    rating: 4,
    text: "Дмитрий помог с крупной техникой и заранее уточнил все детали перевозки.",
    createdAt: "2026-05-18T08:10:00.000Z",
    tripId: "cargo-2",
  },
];

export const mockChats: Chat[] = [];

export const mockChatMessages: ChatMessage[] = [];
